version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "https://github.com/longa16/3DVP_Project/blob/main/super_calculator/Dockerfile"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

